[[manager.prepend_keymap]]
on = ["g", "c"]
run = "cd ~/dev"
desc = "Cd to ~/dev"

[[manager.prepend_keymap]]
on = ["g", "d"]
run = "cd ~/dox"
desc = "Cd to ~/dox"

[[manager.prepend_keymap]]
on = ["g", "D"]
run = "cd ~/dl"
desc = "Cd to ~/dl"

[[manager.prepend_keymap]]
on = ["g", "p"]
run = "cd ~/pix"
desc = "Cd to ~/pix"

[[manager.prepend_keymap]]
on = ["g", "s"]
run = "cd ~/scripts"
desc = "Cd to ~/scripts"

[[manager.prepend_keymap]]
on = ["g", "t"]
run = "cd ~/temp"
desc = "Cd to ~/temp"

