[manager]
ratio = [1, 3, 4]
sort_by = "alphabetical"
sort_sensitive = false
sort_reverse = false
sort_dir_first = false
linemode = "size"
show_hidden = false
show_symlink = true

[preview]
tab_size = 2
max_width = 600
max_height = 900
