[manager]
ratio = [1, 4, 3]
sort_by = "none"
sort_sensitive = false
sort_reverse = false
sort_dir_first = false
linemode = "none"
show_hidden = true
show_symlink = true

[preview]
tab_size = 2
max_width = 600
max_height = 900
